import { useRouter } from 'next/router';
import { doc, getDoc } from 'firebase/firestore';
import db from '../../FirebaseConfig';
import { useContext, useEffect, useState } from 'react';
import { ProfileNavContext, UserContext } from '@/Context';
import Image from 'next/image';
import userPlaceholder from '../../../public/assets/user.png'
import Header from '@/Components/Profile/Header';
import styles from '@/styles/Profile.module.css'
import Head from 'next/head';
import BodyNav from '@/Components/Profile/BodyNav';
import PersonalDetail from '@/Components/Profile/PersonalDetail';
import WorkExperience from '@/Components/Profile/WorkExperience';
import Education from '@/Components/Profile/Education';
import Skills from '@/Components/Profile/Skills';


export default function Page() {
    const router = useRouter();
    const urlQuery = router.query.userId;
    const { user, setUser } = useContext(UserContext);
    const [userDB, setUserDB] = useState([])
    const [profileNav, setProfileNav] = useState("")

    useEffect(() => {
        const readData = async () => {
            if (urlQuery) {
                const docRef = doc(db, 'users', urlQuery);
                const docSnap = await getDoc(docRef);
                if (docSnap.exists()) {
                    setUserDB(docSnap.data());
                } else {
                    console.log('No such document!');
                }
            }
            // console.log();
        };
        readData();

    }, [urlQuery, setUser]);
    


    return (
        <>
            <Head >
                <title>Profile</title>
                <meta name="descriFption" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.profileWrap} >
                <Header userDB={userDB} />
                <ProfileNavContext.Provider value={{ profileNav, setProfileNav }} >
                    <div className={styles.body}>
                        <div className={styles.floatingSection}>
                            <BodyNav />
                        </div>
                        <div className={styles.mainContent}>
                            <PersonalDetail userDB={userDB} />
                            <WorkExperience userDB={userDB} />
                            <Education userDB={userDB} />
                            <Skills userDB={userDB} />
                        </div>
                    </div>
                </ProfileNavContext.Provider>

            </div>
        </>
    );
}
