import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/Components/Header'
import HeroSection from '@/Components/HomePage/HeroSection'
import SecondSection from '@/Components/HomePage/SecondSection'
import { Candidate } from '@/Components/HomePage/Candidate'
import Recruit from '@/Components/HomePage/Recruit'
import FindYouCandidate from '@/Components/HomePage/findYouCandidate'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Header />
        <HeroSection />
        <SecondSection />
        <Candidate />
        <Recruit />
        <FindYouCandidate />
      </main>
    </>
  )
}
