import Landing from '@/Components/Landing/Landing'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Talnio</title>
        <meta name="descriFption" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
          <Landing />
      </main>
    </>
  )
}
