import Head from 'next/head'
import { useContext, useState } from 'react'
import { CompanyDetailsContext, PersonalDetailsContext, RegisterStageContext, } from '@/Context'
import Header from '@/Components/RegisterComapny/Header';
import styles from '@/styles/RegisterCompany.module.css'
import PersonalDetails from '@/Components/RegisterComapny/PersonalDetails';
import CompanyDetails from '@/Components/RegisterComapny/CompanyDetails';
import ThankYou from '@/Components/RegisterComapny/ThankYou';

export default function ResumeBuilder() {
    const { registerStage } = useContext(RegisterStageContext);

    const [personalDetails, setPersonalDetails] = useState({
        firstName: '',
        middleName: '',
        lastName: '',
        mobileNumber: '',
        emailAddress: '',
    });

    const [companyDetails, setCompanyDetails] = useState({
        companyName: '',
        companyEmail: '',
        designation: '',
        address: '',
        pincode: '',
    });



    return (
        <>
            <Head>
                <title>Resume Builder</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.registerWrap} >
                <Header />
                <PersonalDetailsContext.Provider value={{ personalDetails, setPersonalDetails }}>
                    <CompanyDetailsContext.Provider value={{ companyDetails, setCompanyDetails }}>
                        {registerStage === "Personal Details" ? <PersonalDetails /> : registerStage === "Company Details" ? <CompanyDetails /> : <ThankYou />}
                    </CompanyDetailsContext.Provider>
                </PersonalDetailsContext.Provider>
            </main>
        </>
    )
}

